version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
  client:
    build: ./client
    volumes:
      - ./client/src:/app/src
      - client-modules:/app/node_modules
volumes:
  client-modules: