version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
  api:
    build: ./app
    volumes:
      - ./app/src:/app/src
      - api_modules:/app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - nginx
volumes:
  api_modules: